title: "codercuy"
email: codersitedev@gmail.com
timezone: UTC
baseurl: ""
url: "https://codercuy.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: "/:title/"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
author: Moises Gamio
paginate: 30
disqus: 'codercuy'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed

# Authors
authors:
  moises:
    name: Moises
    display_name: Moises Gamio
    avatar: 'assets/images/author.jpg'
    email: codersitedev@gmail.com
    web: https://codersite.dev/
    twitter: https://twitter.com/MoisesGamio
    description: "Software Engineer. Comprehensive experience in all phases of the software development lifecycle for several economic sectors."

# Social
social:
  medium: https://medium.com/@mkgv89
  facebook: https://www.facebook.com/codersite.dev
  twitter: https://twitter.com/MoisesGamio

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives

google_analytics: G-LMP8PBTBG2

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "pub-9154513114335042"
adsense-data-ad-slot: "1269872539"